### ISSUE TITLE
Where should be placed the config file?

### ISSUE THREAD

**Issue by qgadrian** [Vincit/gocd-slack-task#4]
Where should be placed the config file?

The readme says nothing about it.

Thanks!

**Comment by juhasipo** [comment]
There is no config file at the moment. All the configurations are given in the GoCD UI after you add the Slack task to your job.

**Comment by qgadrian** [comment]
Ok! I made a PR to make the clear the correct plugin usage.

Thank you @juhasipo

**Comment by juhasipo** [comment]
@qgadrian   I merged your change now. Thanks for your contribution!

**Comment by qgadrian** [comment]
Nice, glad to help!
