### ISSUE TITLE
Did not find 'task' plugin with id 'slack.task'. Looks like plugin is missing

### ISSUE THREAD

**Issue by VR6Pete** [Vincit/gocd-slack-task#7]
Running GoCD 18.5.0.

When the slack task is added to a template I am getting the following error in the pipeline console log.

[go] Task: Plugin with ID: slack.task took: 0.0s.
Error: Did not find 'task' plugin with id 'slack.task'. Looks like plugin is missing.

Could you please advise if a plugin update is required to make it compatible or if there is another issue here?

**Comment by juhasipo** [comment]
I tested the plugin with GoCD 18.5.0 and it seems to work fine. 

Are you using elastic agents? Previously I've encountered similar issue when the agent is just starting up: https://github.com/gocd/gocd/issues/2872

**Comment by VR6Pete** [comment]
We are not using elastic agents, this is the set up as a task at the end against a single stage pipeline, defiantly not due to agents starting up as the job was running for a good 20 minutes before the slack task attempted to run. 

Is there any further logging I can look at?

Cheers

**Comment by juhasipo** [comment]
You can try to look if there is anything interesting in the GoCD server's `go-server.log` and agent's `go-agent.log` files.

One thing you could also try to check is that has the agent fetched the plugin correctly. The JAR file should be in the `<go agent>/plugins/external` directory. There should also be `<go agent>/plugins/go-plugins-all.zip` file with all the available plugins. Might be a bit far fetched but one reason might be that the JAR file permissions aren't correct and the server/agent can't access the plugin's JAR file.

If that doesn't have any additional information you could also try to turn on some additional debug logging on the GoCD agent. Possibly for the `com.thoughtworks.go.plugin` package or for the whole `com.thoughtworks.go` package (which may give tons of addition logging).

**Comment by VR6Pete** [comment]
That might not be as far fetched as you think with the permissions as running across different domains and have suffered a few permission issues as part of a migration. 

Thanks for the reply, certainly enough here to help me on my way. Will report back next week 👍🏻

**Comment by juhasipo** [comment]
Closing this for now. In case there are more problems I'll re-open the issue.
